### PR TITLE
Include dependencies in setup.py

### PR DESCRIPTION
**Pull request by TRManderson**
Most of your other packages could also do with this treatment honestly

### CODE REVIEW

**Comment by dlo** [comment]
I've done this in the past, but worried about overriding dependencies automatically from other projects that might be installed in the same virtual environment. Is there a way around that?

**Comment by dlo** [comment]
(BTW, thank you!)

**Comment by TRManderson** [comment]
That's actually a really important thing to bring up that I honestly hadn't considered. The best you can do is provide as loose a bound on version requirements as possible.

When it comes to Python, I primarily develop libraries rather than executables, so I'm used to trying to make the bounds loose, but executable development is a very different thing and I'm honestly not sure of best practices. Maybe just leave this PR sitting here for now :/

**Comment by dlo** [comment]
Will do. 😊

**Comment by TRManderson** [comment]
Just closing this because my knowledge hasn't progressed at all wrt this

**Pull request closed without merging**
